### PR TITLE
Add proposal for restructuring of resource loader

### PR DESCRIPTION
**Pull request by SheepFromHeaven**

### CODE REVIEW

**Comment by jurekbarth** [comment]
I would like to see a more promised based approach. Promises are widely supported and a polyfill is small.
ES6 dynamic imports may be a good starting point for an interface https://github.com/tc39/proposal-dynamic-import.

**Review by jurekbarth — CHANGES_REQUESTED** [review]
I would like to see a more promised based approach. Promises are widely supported and a polyfill is small.
ES6 dynamic imports may be a good starting point for an interface https://github.com/tc39/proposal-dynamic-import.

**Comment by timomayer** [comment]
Some of the points in the rfc are already opened as issues: for example:
https://github.com/biotope/biotope-resource-loader/issues/1

I ll add @alxbenz to the reviewers. they are responsible for the loader

**Comment by SheepFromHeaven** [comment]
Also important for biotope/biotope-resource-loader#4

**Comment by SheepFromHeaven** [comment]
@biotope/core-enforcer this one seems to be done now 😆

**Pull request closed without merging**
